name: CD-github-action

on: 
  push: 
    branches: 
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      FRONTEND_APP_NAME: "gitops-frontend"
      BACKEND_APP_NAME: "gitops-backend"

    steps:
      - uses: actions/checkout@v3

      - name: Set Up Git Identity
        run: |-
          git config --global user.name ${{ secrets.ACTOR }}
          git config --global user.email ${{ secrets.ACTOR_EMAIL }}

      - uses: actions/checkout@v4

      - name: Generate tag
        run: |-
          TAG_NAME="v1.0.${{ github.run_number }}"

          echo "VERSION='${TAG_NAME}'" >> $GITHUB_ENV

      - name: Create and Push Git Tag
        run: |
          if git rev-parse "$VERSION" >/dev/null 2>&1; then
            echo "Tag $VERSION already exists. Skipping..."
          else
            git tag "$VERSION"
            git push origin "$VERSION"
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push container frontend
        working-directory: ./frontend
        run: |-
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/${{ env.FRONTEND_APP_NAME }}:${VERSION}"

          docker build -f ./dockerfile -t "${IMAGE_NAME}" .
          docker push "${IMAGE_NAME}"

      - name: Build and push container backend
        working-directory: ./backend
        run: |-
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/${{ env.BACKEND_APP_NAME }}:${VERSION}"

          docker build -f ./dockerfile -t "${IMAGE_NAME}" .
          docker push "${IMAGE_NAME}"