name: CI-github-action

on:
  pull_request:
    branches:
      - develop
  push: 
    branches: 
      - develop

jobs:
  testing:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v4

      - name: Install MySQL Client
        run: sudo apt-get install -y mysql-client

      - name: Wait for MySQL
        run: |
          for i in {30..0}; do
            if mysqladmin ping -h127.0.0.1 -u $MYSQL_USER -p$MYSQL_PASSWORD --silent; then
              echo "MySQL is up!";
              break;
            fi
            echo 'Waiting for MySQL...';
            sleep 2;
          done

      - name: Run a sample MySQL command
        run: |
          mysql -h 127.0.0.1 -u $MYSQL_USER -p$MYSQL_PASSWORD -e "SHOW DATABASES;"
