name: CI-github-action

on:
  pull_request:
    branches:
      - develop
  push: 
    branches: 
      - develop

jobs:
  testing:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h localhost" --health-interval=10s --health-timeout=5s --health-retries=3

      minio:
        image: minio/minio:latest
        ports:
          - 9000:9000
          - 9001:9001
        options: >-
          --health-cmd "curl -f http://localhost:9000/minio/health/live || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3
        command: server /data --console-address ":9001"

    steps:
      - uses: actions/checkout@v4

      - name: Install MySQL Client
        run: sudo apt-get install -y mysql-client

      - name: Wait for MySQL
        run: |
          for i in {30..0}; do
            if mysqladmin ping -h127.0.0.1 -uroot -p${{ secrets.MYSQL_ROOT_PASSWORD }} --silent; then
              echo "MySQL is up!";
              break;
            fi
            echo 'Waiting for MySQL...';
            sleep 2;
          done

      - name: Install MinIO Client (mc)
        run: |
          curl -O https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          sudo mv mc /usr/local/bin/

      - name: Configure MinIO Client
        run: |
          mc alias set myminio http://127.0.0.1:9000 ${{ secrets.MINIO_ACCESS_KEY }} ${{ secrets.MINIO_SECRET_KEY }}

      - name: Create a Bucket
        run: mc mb myminio/${{ secrets.MINIO_BUCKET_NAME }}

      - name: Copy evironment file
        run: cp .env.example .env

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        working-directory: ./backend
        run: |
                python -m pip install --upgrade pip
                pip install -r requirement.txt

      - name: Run Tests
        working-directory: ./backend
        run: |
          pytest
